name: Deploy

on:
  push:
    branches:
      - version2
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Make envfile
      uses: SpicyPizza/create-envfile@v1
      with:
        envkey_DEBUG: false
        envkey_NOTION_AUTH: ${{ secrets.NOTION_AUTH }}
        envkey_NOTION_COURSE_FRONTEND: ${{ secrets.NOTION_COURSE_FRONTEND }}
        envkey_NOTION_COURSE_FRONTEND_2: ${{ secrets.NOTION_COURSE_FRONTEND_2 }}
        envkey_NOTION_COURSE_MOBILE: ${{ secrets.NOTION_COURSE_MOBILE }}
        envkey_FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        envkey_FIREBASE_ENV: ${{ secrets.FIREBASE_ENV }}
        envkey_FIREBASE_APIKEY: ${{ secrets.FIREBASE_APIKEY }}
        envkey_FIREBASE_AUTHDOMAIN: ${{ secrets.FIREBASE_AUTHDOMAIN }}
        envkey_FIREBASE_DATABASEURL: ${{ secrets.FIREBASE_DATABASEURL}}
        envkey_FIREBASE_PROJECTID: ${{ secrets.FIREBASE_PROJECTID }}
        envkey_FIREBASE_STORAGEBUCKET: ${{ secrets.FIREBASE_STORAGEBUCKET }}
        envkey_FIREBASE_SENDERID: ${{ secrets.FIREBASE_SENDERID }}
        envkey_FIREBASE_APPID: ${{ secrets.FIREBASE_APPID }}
        envkey_FIREBASE_MEASUREMENTID: ${{ secrets.FIREBASE_MEASUREMENTID }}
        envkey_ADMIN_TYPE: ${{ secrets.ADMIN_TYPE }}
        envkey_ADMIN_PROJECT_ID: ${{ secrets.ADMIN_PROJECT_ID }}
        envkey_ADMIN_PRIVATE_KEY_ID: ${{ secrets.ADMIN_PRIVATE_KEY_ID }}
        envkey_ADMIN_PRIVATE_KEY: ${{ secrets.ADMIN_PRIVATE_KEY }}
        envkey_ADMIN_CLIENT_EMAIL: ${{ secrets.ADMIN_CLIENT_EMAIL }}
        envkey_ADMIN_CLIENT_ID: ${{ secrets.ADMIN_CLIENT_ID }}
        envkey_ADMIN_AUTH_URI: ${{ secrets.ADMIN_AUTH_URI }}
        envkey_ADMIN_TOKEN_URI: ${{ secrets.ADMIN_TOKEN_URI }}
        envkey_ADMIN_AUTH_PROVIDER_X509_CERT_URL: ${{ secrets.ADMIN_AUTH_PROVIDER_X509_CERT_URL }}
        envkey_ADMIN_CLIENT_X509_CERT_URL: ${{ secrets.ADMIN_CLIENT_X509_CERT_URL }}
        envkey_EMAILS_MAIN_SENDER_EMAIL: ${{ secrets.EMAILS_MAIN_SENDER_EMAIL }}
        envkey_EMAILS_MAIN_SENDER_APIKEY: ${{ secrets.EMAILS_MAIN_SENDER_APIKEY }}
        envkey_EMAILS_MENTOR_FRONTEND_EMAIL: ${{ secrets.EMAILS_MENTOR_FRONTEND_EMAIL }}
        envkey_EMAILS_MENTOR_MOBILE_EMAIL: ${{ secrets.EMAILS_MENTOR_MOBILE_EMAIL }}
        envkey_EMAILS_JS_PUBLIC_KEY: ${{secrets.EMAILS_JS_PUBLIC_KEY}}
        envkey_EMAILS_JS_SERVICE_ID: ${{secrets.EMAILS_JS_SERVICE_ID}}
        envkey_EMAILS_JS_TEMPLATE_ID: ${{secrets.EMAILS_JS_TEMPLATE_ID}}
        file_name: .env

    - name: Install packages
      run: |
        npm install -g firebase-tools
        npm install
        npm run init:env

    - name: Build notion
      run: |
        npm run build:notion

    - name: Build app
      run: |
        npm run build:app

    - name: Deploy notion
      run: |
        npm run deploy:notion

    - name: Deploy app
      run: |
        cd firebase
        firebase deploy --only hosting,database --token ${{ secrets.FIREBASE_TOKEN }}

    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.36.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true


